### ISSUE TITLE
Backend: Implement Bulk Link Creation API Endpoint

### ISSUE THREAD

**Issue by Bhavishya-T** [CSC510SEFall24/URL-Shortener-2.0#2]
Develop an API endpoint that accepts multiple URLs and returns their corresponding short links.

Tasks:
- Define the API request format to accept multiple URLs.
- Implement logic for generating short links in bulk.
- Ensure each URL is processed independently for error handling.

**Comment by vyompatel77** [comment]
Completed the required tasks in Backend and updated code.

**Comment by vyompatel77** [comment]
Updated code to do the following defined tasks in backend
