### ISSUE TITLE
Frontend: Bulk Link Creation UI Implementation

### ISSUE THREAD

**Issue by Bhavishya-T** [CSC510SEFall24/URL-Shortener-2.0#3]
Implement the UI for the bulk link creation feature based on discussion.

Tasks:
- Connect the frontend form to the bulk creation API.
- Display generated short links in a user-friendly format.
- Include error messages for failed URL creations.

**Comment by vyompatel77** [comment]
Solved the issues in frontend and updated code and also made short links display user friendly

**Comment by vyompatel77** [comment]
Solved the issues in frontend and updated code and also made short links display user friendly
