### ISSUE TITLE
Backend: Implement Expiration by Visits Logic

### ISSUE THREAD

**Issue by Bhavishya-T** [CSC510SEFall24/URL-Shortener-2.0#6]
Set up logic to track clicks and deactivate links after a specified number.

Tasks:
- Update link model to track click count.
- Set expiration threshold and deactivate logic.

**Comment by rarchitgupta** [comment]
Will be closed with PR: https://github.com/CSC510SEFall24/URL-Shortener-2.0/pull/1
Completed by @vyompatel77
